services:
  - type: web
    name: devdale-agency
    env: node
    plan: free
    buildCommand: pnpm install && pnpm run build
    startCommand: pnpm start
    healthCheckPath: /api/ping
    envVars:
      - key: NODE_VERSION
        value: 20.0.0
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: FROM_EMAIL
        sync: false
      - key: ADMIN_EMAIL
        sync: false
